import org.junit.Test;
import sample.AcoustID.AcoustIDJson.Results;
import sample.Utilities.HttpReader;
import sample.AcoustID.MusicBrianzJson.MusicBrainzResult;

import java.io.IOException;

import static junit.framework.Assert.assertFalse;
import static junit.framework.TestCase.assertEquals;
import static junit.framework.TestCase.assertNotNull;

public class HttpToJson {

    @Test

    public void getAudioTags() throws IOException, IndexOutOfBoundsException {


        HttpReader json= new HttpReader();
        String url="https://api.acoustid.org/v2/lookup?client=DPBREMyuby&meta=recordings+releasegroups+compress&duration=129&fingerprint=AQADtIm6RMqiTPiHPIf7Af-Rm2ir4x-F57iGPsH-sggPc3zxRDl4Hfc4nEgzfqgP7YSP6ugLkRda6jh-FP5x-ALzoYck7Q2O_DhhTcWHZ2kOP0gd9jB5aJuQnUJPHs2X4dGO_OgP8cQf5Ee_DuGPHw19HNoywT_Owh8eHekzkXhffAfFG8XRH6m6Qy9OIz78HX8qnKBOxNpMWNBl4XAK9bhk5LhOOO7RB5H1Qz9KHbkOZ9FxbkdaUXihHyeRqkflGjnaDD4liDte45KQ4ytxOD_eoA1-hB-aQz1T4UZePmgeoWeOoI1cyN6H_sUZIuhxF9-PnMFF3Ic-HOmHXh9-3KHRxEeeC-I_hA16NPvxRHie4Idf5NCoXPDkww-Nf7iNY3KS5LiQHmz248wT_EaDnj_eJHimHOTEG312NKdx7MuHZ8eJPA_0XcF1xE0uHM3RM8Sn4fpxVM7iEL6OfD3E-AivHGeP_8EX1JvhI5meI9_xSSKu5PjRI4ya4RRz6NmF49B-NFmUrPgX7Og0Glo6Hg9xfeiPZt0hORyeF_3x6EOuF8fBMvhY_NiqCG_Q38h3yMbFI8yPPqgHwxd-hD905DF-9D2MGvWOPrKQ49qFlymaNUN7_ND-I60PvwJ66fjxbB-6-MIv5FDNFLkO__jhiIzR5jhzhAkBzWKMfgfOw0d4HBeanJisHZ2QvkefiJCOHD3-w2N28HjpoRfGHuEJcZyQz_BXtCP6G44-hD_0ZAj3C66L80ejq8KFqyT6EY6GZB1irQ7e4tuOG0ePa0eOxoqO45G2QqU--BJ-IwhTLUeffPgtaLl21G7w9si54kdY6hJ8aMgt4UenEc2o4RlR92hUGl-SIQx_aHyQh8aX40f3BOmFZCT-Ez9-TejR_PjxDQ33AcePyj_aHP404VhbwzyOHD-klDyOZrtRD4cGH-kzkOkDM8lRyshedE1EaCm4fgitwKN0tI_R5EeWrcd9aDlH9Dl-hHHo4VngI9SFZxUaRm8xobJGhLmwo-Xh8MSRS6Hxg62IH36OsBLyE_UdNPKOS2KMwid64cJ9QSO-BF-QaddwKssH30YenDn0Ez-8F9dQqy-OHl53tDm-HH2H9Kh8XDLCP3BV6Pzw5-AP_4Ipo2dxXWhESah93EL_YkrU4cfxFM0I7cd5PCGFx0IOlOLxKKGe4D7yoFaWCHXCw-gPPUpkfMPMHGe2QIoVfEGf4vdRH_7Bb8dxEj4-3MMpGTle-KCz46BJ5McP6Tj8AX7w6oLDQ5dxKhGs40f-4DCzrEJodD_s44dLQT8evHj248KPQ99xDn8OWz_QEyUO8wo-Hd-hg-eKH3Zx52ge6AxOCuURLz6-o8uF8Bn8Az_0AT8eC_oKxzh8nA9-UOMOnSX84sp0QufxgTxSkuDwIT8P6tAxUTieJDpOSYd8fOdxZUE5QQx14ydisRbapbiP3ci-JESSJ8eP_7gePEN6L4GeK0beDG9wNEuU6Ah_JGl0_LGCPTkuHT3OLLgyIfzRqA_qRWvwSji07GiX4yzyuEXOJ2ieKIdm0WgQLiSeJT_OI_1ihbisQWdwGU20Hi3D4_mhIw_65bhG_Jh5XLB1wWNPpPwxvbh0KOoKnz3q6bhutMemHNqJpkP5qOijcBAZEyWZ4wm6vCKcLcsxLzgP_9BVHNt6tA8uTP_gH-UZvEXrww-0Mzi0L6Aq4uEKc8Q95OwBH-_h47Lwgzcu5CJc6FaPw1lXdN7xB_qSGVcEjw8u6HyGH3nyFZV7pPuI_riCvEduNajMIzcL58MtpJDsCyF1_DjqrYMfo8uQH_2hH3b24cd_fDRxwS908IgX-MSPF_wc5DWuwCfk4scD6S5e5UDK7ELPoz_O4tmmPLCD58GbIz3xjTds8dBz_EiPos9V_Dji6oEJ3ThyUaBenPjB90jRgzTRvEf7g-EPvw5-Fof_oj2KF3-gv7BWHN92OMJ5MNbxBGUPHT7OE6VSfBduodHDo8d1nAKP6vCD48cJHzcPnDmeDCdOMeiPW-iz49FxaR6K_gF14sFF_DnsaMfn44dO6fhZiD-uw9SFXkf1FM2JK1fxF5eNpj9C8sMPJlzR63iOMDfaFdIv4dTxI_wX_EgPV4R8OaCc42OOH-VxvDhCkYfHD52yxfiKHzePUNdxQWcAMzpuHF-IE-LxgOvxCX7QC8-P7odx0D9-3LmAHz9uGK9S-EcpJsE_HJ-IkzG0PkYT4Y_whMRRLtmhwxTCmfiPvvCDCzAZXUjxQ4e_4Dv444flhQR0dsZXGEVvmHwM3fgv5PCP3ALEEFbMAEYAEI4gAIiQAFDhBCYWMwGsM0JpoYmwkjCngCJECiKMAYEKICRlRAEnjQKUCIMMA0gKUhRBBhJACBfKBMQGIgQAoyAESCgHgVFOCQekccZgxgQCDAAhjGDCEMaAIAgYZS0QgAqMEAFMAAYEEJhUAZigCDIuCBHACAEEEkIowAZRAAEmCIEEXEGQMAQQQCwwRBgAiAJCCWEEchwQAiQRRhEBFFFCAAEFYcAYMg6BSgmjkFAGCEKIEQABAAhBSDBAqDACKCGcIEQwYhwBxjkoEHAMcEIhIIAITZQRQAFhmGICCSmYMYABIBgiTDAANWLiEYCgAQAgBAAAxlAAtHOGQSKARIgwIwgAACkKLAQWIIIgMsAJJ5hRTAhmsUGCGAIkIIAIYERg2DFgFQEMUEKIIQIhAgADQjEggABSIEAMQEpQQQADQCkjkCAACuCEIIIRwoRxHjFAsDLCAACQAkIhqBhRwAgHAADWICUMVVZRCRAUECFgIDMAKaScAA4SApwyBgAERHCGCGUEd45QByRzBAmBGCAOCAIEkwoDIcgwBlADsBCKkUAGMQKRJYCQACCEBCPGEUOAFIQBQYQSRgFogAOEGCQUAQggpqBhAAlgiACAAYUgUEIAKoYgxhlEhANCCSAUAoAIIYASggkFlAkOEKEEEgIIJJkQChAqDABWJAEcQQxA4hAwDBEmhHFKCAAAFMwBgBgRSgAgHAIAIOC5ckoCZQSBTBBCIFDMGSCBUAAIIxhTShiErDQgKEYBEQgAgAQDwhGBBGNIAQMBYc4Yt5xAAghDIgECICosQUAxoRgglBIggFFASEEBEEIYDAAASBCIiDDAKMGIAwggYJQyRiBoIAFAaIGBsQRaxaRwTABABFbMMgMAcwxQhQACVhEnBAGeAmSEAkA4ogCQIEghjEIQWKGAUcZQgQwwRghhBCIA";

        Results results= json.getJSONFromUrl(url, Results.class);

        assertEquals(results.getResults().get(0).getRecordings().get(0).getReleaseGroups().get(0).getTitle(), "Quadrophenia");





    }



    @Test

    public void getMuiscBrainzTags() throws IOException {


        HttpReader json= new HttpReader();

        String url="https://musicbrainz.org/ws/2/recording/cd2e7c47-16f5-46c6-a37c-a1eb7bf599ff?inc=artists+releases&fmt=json";
        MusicBrainzResult results= json.getJSONFromUrl(url, MusicBrainzResult.class);

        assertEquals(results.getTitle(), "Lower Your Eyelids to Die With the Sun");





    }


}
